name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade build twine commitizen

      - name: Update pyproject.toml and Generate Changelog
        run: |
          RELEASE_VERSION=${{ github.event.release.tag_name }}
          echo "Releasing version $RELEASE_VERSION"

          # Wechsle auf main (verhindert "detached HEAD" Problem)
          git checkout main

          # Setzt die neue Version in pyproject.toml
          sed -i "s/^version = .*/version = \"$RELEASE_VERSION\"/" pyproject.toml

          # Generiere den Changelog
          cz changelog
          
          # Commit & Push der neuen Version und CHANGELOG.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add pyproject.toml CHANGELOG.md
          git commit -m "chore(release): update version to $RELEASE_VERSION and update CHANGELOG"
          git push origin main
          
      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
